-- Alex_C.T Smart Plex modular Profilarr v2 PCD operations.
-- 01: Core tags, languages, and quality names.
-- Import first.

INSERT OR REPLACE INTO tags (name) VALUES ('Smart Plex');
INSERT OR REPLACE INTO tags (name) VALUES ('Language');
INSERT OR REPLACE INTO tags (name) VALUES ('Subtitles');
INSERT OR REPLACE INTO tags (name) VALUES ('Codec');
INSERT OR REPLACE INTO tags (name) VALUES ('HDR / 4K');
INSERT OR REPLACE INTO tags (name) VALUES ('Audio');
INSERT OR REPLACE INTO tags (name) VALUES ('Blocking');
INSERT OR REPLACE INTO tags (name) VALUES ('Scoring');
INSERT OR REPLACE INTO tags (name) VALUES ('Movies');
INSERT OR REPLACE INTO tags (name) VALUES ('Series');
INSERT OR REPLACE INTO tags (name) VALUES ('Radarr');
INSERT OR REPLACE INTO tags (name) VALUES ('Sonarr');
INSERT OR REPLACE INTO tags (name) VALUES ('1080p');
INSERT OR REPLACE INTO tags (name) VALUES ('4K');
INSERT OR REPLACE INTO tags (name) VALUES ('Catalog');
INSERT OR REPLACE INTO tags (name) VALUES ('720p');
INSERT OR REPLACE INTO tags (name) VALUES ('Archive');
INSERT OR REPLACE INTO tags (name) VALUES ('Editions');
INSERT OR REPLACE INTO tags (name) VALUES ('Release Fixes');
INSERT OR REPLACE INTO languages (name) VALUES ('Any');
INSERT OR REPLACE INTO languages (name) VALUES ('English');
INSERT OR REPLACE INTO languages (name) VALUES ('Spanish');
INSERT OR REPLACE INTO qualities (name) VALUES ('Raw-HD');
INSERT OR REPLACE INTO qualities (name) VALUES ('BR-Disk');
INSERT OR REPLACE INTO qualities (name) VALUES ('Remux-2160p');
INSERT OR REPLACE INTO qualities (name) VALUES ('Bluray-2160p');
INSERT OR REPLACE INTO qualities (name) VALUES ('WEBDL-2160p');
INSERT OR REPLACE INTO qualities (name) VALUES ('WEBRip-2160p');
INSERT OR REPLACE INTO qualities (name) VALUES ('HDTV-2160p');
INSERT OR REPLACE INTO qualities (name) VALUES ('Remux-1080p');
INSERT OR REPLACE INTO qualities (name) VALUES ('WEBDL-1080p');
INSERT OR REPLACE INTO qualities (name) VALUES ('Bluray-1080p');
INSERT OR REPLACE INTO qualities (name) VALUES ('WEBRip-1080p');
INSERT OR REPLACE INTO qualities (name) VALUES ('HDTV-1080p');
INSERT OR REPLACE INTO qualities (name) VALUES ('Bluray-720p');
INSERT OR REPLACE INTO qualities (name) VALUES ('WEBDL-720p');
INSERT OR REPLACE INTO qualities (name) VALUES ('WEBRip-720p');
INSERT OR REPLACE INTO qualities (name) VALUES ('HDTV-720p');
INSERT OR REPLACE INTO qualities (name) VALUES ('Bluray-576p');
INSERT OR REPLACE INTO qualities (name) VALUES ('Bluray-480p');
INSERT OR REPLACE INTO qualities (name) VALUES ('WEBDL-480p');
INSERT OR REPLACE INTO qualities (name) VALUES ('WEBRip-480p');
INSERT OR REPLACE INTO qualities (name) VALUES ('DVD-R');
INSERT OR REPLACE INTO qualities (name) VALUES ('DVD');
INSERT OR REPLACE INTO qualities (name) VALUES ('DVDSCR');
INSERT OR REPLACE INTO qualities (name) VALUES ('SDTV');
INSERT OR REPLACE INTO qualities (name) VALUES ('Telecine');
INSERT OR REPLACE INTO qualities (name) VALUES ('Telesync');
INSERT OR REPLACE INTO qualities (name) VALUES ('REGIONAL');
INSERT OR REPLACE INTO qualities (name) VALUES ('WORKPRINT');
INSERT OR REPLACE INTO qualities (name) VALUES ('CAM');
INSERT OR REPLACE INTO qualities (name) VALUES ('Unknown');
INSERT OR REPLACE INTO qualities (name) VALUES ('Remux-1080p');
INSERT OR REPLACE INTO qualities (name) VALUES ('Remux-2160p');
