-- Alex_C.T Media Server modular Profilarr v2 PCD operations.
-- 02: Language and subtitle regular expressions.
-- Requires 01.Core-Tags-Languages-Qualities.sql.

INSERT OR REPLACE INTO regular_expressions (name, pattern, description) VALUES ('Language: Prefer English + Spanish', '(?i)^(?:(?=.*(?:\beng(?:lish)?\b|\btrueenglish\b|\bingles\b|\bingl[e\u00e9]s\b|[._ \-\[\(](?:en|eng|enus)[._ \-\]\)]))(?=.*(?:(?:\bspa(?:nish)?\b|\besp(?:anol|a\u00f1ol)?\b|\bespanol\b|\bespa\u00f1ol\b|\bcastellano\b|\bcastilian\b)|(?:\blatino\b|\blatina\b|\blatam\b|\blatin[ ._-]?america(?:n)?\b|\blatinoamerica(?:no)?\b|\blatinoam[e\u00e9]rica(?:no)?\b|\bespa[n\u00f1]ol[ ._-]?latino\b|\blat(?:ino)?[ ._-]?dub(?:bed)?\b|\baudio[ ._-]?(?:latino|latam|spanish|espa[n\u00f1]ol)\b|\bcast(?:ellano)?\b|\bmex(?:ican|ico)?\b|\bmx\b|\bes[ ._-]?(?:la|lat|419|mx|es|us)\b|\bspa[ ._-]?(?:lat|la|mx|cast|es|419)\b|\besp[ ._-]?(?:lat|la|mx|cast|es|419)\b|[._ \-\[\(](?:es|spa|esp|lat|la|mx|es419)[._ \-\]\)])))|(?=.*(?:\blatino\b|\blatina\b|\blatam\b|\blatin[ ._-]?america(?:n)?\b|\blatinoamerica(?:no)?\b|\blatinoam[e\u00e9]rica(?:no)?\b|\bespa[n\u00f1]ol[ ._-]?latino\b|\blat(?:ino)?[ ._-]?dub(?:bed)?\b|\baudio[ ._-]?(?:latino|latam|spanish|espa[n\u00f1]ol)\b|\bcast(?:ellano)?\b|\bmex(?:ican|ico)?\b|\bmx\b|\bes[ ._-]?(?:la|lat|419|mx|es|us)\b|\bspa[ ._-]?(?:lat|la|mx|cast|es|419)\b|\besp[ ._-]?(?:lat|la|mx|cast|es|419)\b|[._ \-\[\(](?:es|spa|esp|lat|la|mx|es419)[._ \-\]\)]))(?=.*(?:\bmulti(?:[ ._-]?(?:audio|lang|language|dub|sub|subs))?\b|\bmulti\d+\b|\bmultilang\b|\bmultiaudio\b|\bdual[ ._-]?(?:audio|lang(?:uage)?|dub)?\b|\btri[ ._-]?audio\b|\bdualaudio\b|\bdual\b))|(?=.*(?:\beng(?:lish)?\b|\btrueenglish\b|\bingles\b|\bingl[e\u00e9]s\b|[._ \-\[\(](?:en|eng|enus)[._ \-\]\)]))(?=.*(?:\blatino\b|\blatina\b|\blatam\b|\blatin[ ._-]?america(?:n)?\b|\blatinoamerica(?:no)?\b|\blatinoam[e\u00e9]rica(?:no)?\b|\bespa[n\u00f1]ol[ ._-]?latino\b|\blat(?:ino)?[ ._-]?dub(?:bed)?\b|\baudio[ ._-]?(?:latino|latam|spanish|espa[n\u00f1]ol)\b|\bcast(?:ellano)?\b|\bmex(?:ican|ico)?\b|\bmx\b|\bes[ ._-]?(?:la|lat|419|mx|es|us)\b|\bspa[ ._-]?(?:lat|la|mx|cast|es|419)\b|\besp[ ._-]?(?:lat|la|mx|cast|es|419)\b|[._ \-\[\(](?:es|spa|esp|lat|la|mx|es419)[._ \-\]\)]))).*$', 'Highest language preference. Rewards releases that appear to include both English and Spanish/Latino language indicators, or a strong Latino/multi-audio signal, so the shared media-server library gets the best bilingual copy first.');
INSERT OR REPLACE INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('Language: Prefer English + Spanish', 'Language');
INSERT OR REPLACE INTO regular_expressions (name, pattern, description) VALUES ('Language: English Marker', '(?i)(?:\beng(?:lish)?\b|\btrueenglish\b|\bingles\b|\bingl[e\u00e9]s\b|[._ \-\[\(](?:en|eng|enus)[._ \-\]\)])', 'Tiny English-tag confirmation bonus. English is treated as the last language fallback, so this exists mainly to confirm the tag rather than drive the decision.');
INSERT OR REPLACE INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('Language: English Marker', 'Language');
INSERT OR REPLACE INTO regular_expressions (name, pattern, description) VALUES ('Language: Spanish Audio Marker', '(?i)(?:(?:\bspa(?:nish)?\b|\besp(?:anol|a\u00f1ol)?\b|\bespanol\b|\bespa\u00f1ol\b|\bcastellano\b|\bcastilian\b)|(?:\blatino\b|\blatina\b|\blatam\b|\blatin[ ._-]?america(?:n)?\b|\blatinoamerica(?:no)?\b|\blatinoam[e\u00e9]rica(?:no)?\b|\bespa[n\u00f1]ol[ ._-]?latino\b|\blat(?:ino)?[ ._-]?dub(?:bed)?\b|\baudio[ ._-]?(?:latino|latam|spanish|espa[n\u00f1]ol)\b|\bcast(?:ellano)?\b|\bmex(?:ican|ico)?\b|\bmx\b|\bes[ ._-]?(?:la|lat|419|mx|es|us)\b|\bspa[ ._-]?(?:lat|la|mx|cast|es|419)\b|\besp[ ._-]?(?:lat|la|mx|cast|es|419)\b|[._ \-\[\(](?:es|spa|esp|lat|la|mx|es419)[._ \-\]\)]))', 'Standalone Spanish-audio signal for movie scoring. Matches Spanish, Castellano, Latino, LATAM, and related tags without requiring English or multi-audio to be present.');
INSERT OR REPLACE INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('Language: Spanish Audio Marker', 'Language');
INSERT OR REPLACE INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('Language: Spanish Audio Marker', 'Scoring');
INSERT OR REPLACE INTO regular_expressions (name, pattern, description) VALUES ('Language: Spanish-Only Fallback', '(?i)^(?=.*(?:\bspa(?:nish)?\b|\besp(?:anol|a\u00f1ol)?\b|\bespanol\b|\bespa\u00f1ol\b|\bcastellano\b|\bcastilian\b))(?!.*(?:\beng(?:lish)?\b|\btrueenglish\b|\bingles\b|\bingl[e\u00e9]s\b|[._ \-\[\(](?:en|eng|enus)[._ \-\]\)]))(?!.*(?:\bmulti(?:[ ._-]?(?:audio|lang|language|dub|sub|subs))?\b|\bmulti\d+\b|\bmultilang\b|\bmultiaudio\b|\bdual[ ._-]?(?:audio|lang(?:uage)?|dub)?\b|\btri[ ._-]?audio\b|\bdualaudio\b|\bdual\b)).*$', 'Preferred single-language fallback. Rewards explicit Spanish or Castellano tags when a true bilingual English+Spanish release is not available.');
INSERT OR REPLACE INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('Language: Spanish-Only Fallback', 'Language');
INSERT OR REPLACE INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('Language: Spanish-Only Fallback', 'Scoring');
INSERT OR REPLACE INTO regular_expressions (name, pattern, description) VALUES ('Language: Latino Spanish Fallback', '(?i)^(?=.*(?:\blatino\b|\blatina\b|\blatam\b|\blatin[ ._-]?america(?:n)?\b|\blatinoamerica(?:no)?\b|\blatinoam[e\u00e9]rica(?:no)?\b|\bespa[n\u00f1]ol[ ._-]?latino\b|\blat(?:ino)?[ ._-]?dub(?:bed)?\b|\baudio[ ._-]?(?:latino|latam|spanish|espa[n\u00f1]ol)\b|\bcast(?:ellano)?\b|\bmex(?:ican|ico)?\b|\bmx\b|\bes[ ._-]?(?:la|lat|419|mx|es|us)\b|\bspa[ ._-]?(?:lat|la|mx|cast|es|419)\b|\besp[ ._-]?(?:lat|la|mx|cast|es|419)\b|[._ \-\[\(](?:es|spa|esp|lat|la|mx|es419)[._ \-\]\)]))(?!.*(?:\bspa(?:nish)?\b|\besp(?:anol|a\u00f1ol)?\b|\bespanol\b|\bespa\u00f1ol\b|\bcastellano\b|\bcastilian\b))(?!.*(?:\beng(?:lish)?\b|\btrueenglish\b|\bingles\b|\bingl[e\u00e9]s\b|[._ \-\[\(](?:en|eng|enus)[._ \-\]\)]))(?!.*(?:\bmulti(?:[ ._-]?(?:audio|lang|language|dub|sub|subs))?\b|\bmulti\d+\b|\bmultilang\b|\bmultiaudio\b|\bdual[ ._-]?(?:audio|lang(?:uage)?|dub)?\b|\btri[ ._-]?audio\b|\bdualaudio\b|\bdual\b)).*$', 'Secondary Spanish-friendly fallback for Latino, LATAM, Mexican, or ES-style tags that often imply Spanish audio even when English is not clearly labeled.');
INSERT OR REPLACE INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('Language: Latino Spanish Fallback', 'Language');
INSERT OR REPLACE INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('Language: Latino Spanish Fallback', 'Scoring');
INSERT OR REPLACE INTO regular_expressions (name, pattern, description) VALUES ('Language: English-Only Backup', '(?i)^(?=.*(?:\beng(?:lish)?\b|\btrueenglish\b|\bingles\b|\bingl[e\u00e9]s\b|[._ \-\[\(](?:en|eng|enus)[._ \-\]\)]))(?!.*(?:(?:\bspa(?:nish)?\b|\besp(?:anol|a\u00f1ol)?\b|\bespanol\b|\bespa\u00f1ol\b|\bcastellano\b|\bcastilian\b)|(?:\blatino\b|\blatina\b|\blatam\b|\blatin[ ._-]?america(?:n)?\b|\blatinoamerica(?:no)?\b|\blatinoam[e\u00e9]rica(?:no)?\b|\bespa[n\u00f1]ol[ ._-]?latino\b|\blat(?:ino)?[ ._-]?dub(?:bed)?\b|\baudio[ ._-]?(?:latino|latam|spanish|espa[n\u00f1]ol)\b|\bcast(?:ellano)?\b|\bmex(?:ican|ico)?\b|\bmx\b|\bes[ ._-]?(?:la|lat|419|mx|es|us)\b|\bspa[ ._-]?(?:lat|la|mx|cast|es|419)\b|\besp[ ._-]?(?:lat|la|mx|cast|es|419)\b|[._ \-\[\(](?:es|spa|esp|lat|la|mx|es419)[._ \-\]\)])))(?!.*(?:\bmulti(?:[ ._-]?(?:audio|lang|language|dub|sub|subs))?\b|\bmulti\d+\b|\bmultilang\b|\bmultiaudio\b|\bdual[ ._-]?(?:audio|lang(?:uage)?|dub)?\b|\btri[ ._-]?audio\b|\bdualaudio\b|\bdual\b)).*$', 'Last language fallback. English-only releases stay usable, but they should lose to EN+ES, Spanish, Multi, and Latino-tagged options.');
INSERT OR REPLACE INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('Language: English-Only Backup', 'Language');
INSERT OR REPLACE INTO regular_expressions (name, pattern, description) VALUES ('Language: Multi-Dual Audio Bonus', '(?i)(?:\bmulti(?:[ ._-]?(?:audio|lang|language|dub|sub|subs))?\b|\bmulti\d+\b|\bmultilang\b|\bmultiaudio\b|\bdual[ ._-]?(?:audio|lang(?:uage)?|dub)?\b|\btri[ ._-]?audio\b|\bdualaudio\b|\bdual\b)', 'Middle-tier multilingual bonus. Rewards Multi, Multi5, dual-audio, and dual-language tags, but keeps them below explicit EN+ES and single-language Spanish priorities.');
INSERT OR REPLACE INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('Language: Multi-Dual Audio Bonus', 'Language');
INSERT OR REPLACE INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('Language: Multi-Dual Audio Bonus', 'Audio');
INSERT OR REPLACE INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('Language: Multi-Dual Audio Bonus', 'Scoring');
INSERT OR REPLACE INTO regular_expressions (name, pattern, description) VALUES ('Language: Block Other Languages', '(?i)(?:\b(?:(?:480p|576p|720p|1080p|2160p|4k|uhd|bluray|blu[ ._-]?ray|web[ ._-]?dl|webdl|webrip|web[ ._-]?rip|hdrip|hdtv|bdrip|bd[ ._-]?rip|dvdrip|dvd[ ._-]?rip|remux|xvid|avc|x264|h264|h[ ._-]?264|x265|h265|h[ ._-]?265|hevc|av1|vvc|x266|h266|h[ ._-]?266|hdr|hdr10|hdr10plus|hdr10\+|dv|dovi|dts|ddp|eac3|ac3|aac|atmos|proper|repack|rerip))\b(?:.*[._ \-\[\(])(?:(?:truefrench|french|fre|fra|german|ger|deu|italian|ita|portuguese|por|brazilian|russian|rus|japanese|jpn|korean|kor|chinese|chi|zho|mandarin|cantonese|hindi|hin|tamil|telugu|turkish|tur|polish|pol|dutch|nld|swedish|swe|norwegian|nor|danish|dan|finnish|fin|arabic|ara))(?=[._ \-\]\)]|$)|\b(?:audio|dubbed?|dubs?|lang(?:uage)?|vo|vost(?:fr)?|sub(?:s|titles)?)[ ._:-]+(?:(?:truefrench|french|fre|fra|german|ger|deu|italian|ita|portuguese|por|brazilian|russian|rus|japanese|jpn|korean|kor|chinese|chi|zho|mandarin|cantonese|hindi|hin|tamil|telugu|turkish|tur|polish|pol|dutch|nld|swedish|swe|norwegian|nor|danish|dan|finnish|fin|arabic|ara))\b|\b(?:(?:truefrench|french|fre|fra|german|ger|deu|italian|ita|portuguese|por|brazilian|russian|rus|japanese|jpn|korean|kor|chinese|chi|zho|mandarin|cantonese|hindi|hin|tamil|telugu|turkish|tur|polish|pol|dutch|nld|swedish|swe|norwegian|nor|danish|dan|finnish|fin|arabic|ara))[ ._:-]+(?:audio|dubbed?|dubs?|lang(?:uage)?|vo|sub(?:s|titles)?)\b)', 'Heavy negative score for releases tagged as languages outside the intended English or Spanish-friendly target set, such as French, German, Hindi, Russian, Japanese, and similar tags.');
INSERT OR REPLACE INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('Language: Block Other Languages', 'Language');
INSERT OR REPLACE INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('Language: Block Other Languages', 'Blocking');
INSERT OR REPLACE INTO regular_expressions (name, pattern, description) VALUES ('Subtitles: Prefer English + Spanish', '(?i)^(?=.*(?:subs?|subtitles?|srt|vtt|subbed))(?:(?=.*(?:\beng(?:lish)?\b|\btrueenglish\b|\bingles\b|\bingl[e\u00e9]s\b|[._ \-\[\(](?:en|eng|enus)[._ \-\]\)]))(?=.*(?:(?:\bspa(?:nish)?\b|\besp(?:anol|a\u00f1ol)?\b|\bespanol\b|\bespa\u00f1ol\b|\bcastellano\b|\bcastilian\b)|(?:\blatino\b|\blatina\b|\blatam\b|\blatin[ ._-]?america(?:n)?\b|\blatinoamerica(?:no)?\b|\blatinoam[e\u00e9]rica(?:no)?\b|\bespa[n\u00f1]ol[ ._-]?latino\b|\blat(?:ino)?[ ._-]?dub(?:bed)?\b|\baudio[ ._-]?(?:latino|latam|spanish|espa[n\u00f1]ol)\b|\bcast(?:ellano)?\b|\bmex(?:ican|ico)?\b|\bmx\b|\bes[ ._-]?(?:la|lat|419|mx|es|us)\b|\bspa[ ._-]?(?:lat|la|mx|cast|es|419)\b|\besp[ ._-]?(?:lat|la|mx|cast|es|419)\b|[._ \-\[\(](?:es|spa|esp|lat|la|mx|es419)[._ \-\]\)])))|(?=.*(?:\blatino\b|\blatina\b|\blatam\b|\blatin[ ._-]?america(?:n)?\b|\blatinoamerica(?:no)?\b|\blatinoam[e\u00e9]rica(?:no)?\b|\bespa[n\u00f1]ol[ ._-]?latino\b|\blat(?:ino)?[ ._-]?dub(?:bed)?\b|\baudio[ ._-]?(?:latino|latam|spanish|espa[n\u00f1]ol)\b|\bcast(?:ellano)?\b|\bmex(?:ican|ico)?\b|\bmx\b|\bes[ ._-]?(?:la|lat|419|mx|es|us)\b|\bspa[ ._-]?(?:lat|la|mx|cast|es|419)\b|\besp[ ._-]?(?:lat|la|mx|cast|es|419)\b|[._ \-\[\(](?:es|spa|esp|lat|la|mx|es419)[._ \-\]\)]))(?=.*(?:\bmulti(?:[ ._-]?(?:audio|lang|language|dub|sub|subs))?\b|\bmulti\d+\b|\bmultilang\b|\bmultiaudio\b|\bdual[ ._-]?(?:audio|lang(?:uage)?|dub)?\b|\btri[ ._-]?audio\b|\bdualaudio\b|\bdual\b))|(?=.*(?:\beng(?:lish)?\b|\btrueenglish\b|\bingles\b|\bingl[e\u00e9]s\b|[._ \-\[\(](?:en|eng|enus)[._ \-\]\)]))(?=.*(?:\blatino\b|\blatina\b|\blatam\b|\blatin[ ._-]?america(?:n)?\b|\blatinoamerica(?:no)?\b|\blatinoam[e\u00e9]rica(?:no)?\b|\bespa[n\u00f1]ol[ ._-]?latino\b|\blat(?:ino)?[ ._-]?dub(?:bed)?\b|\baudio[ ._-]?(?:latino|latam|spanish|espa[n\u00f1]ol)\b|\bcast(?:ellano)?\b|\bmex(?:ican|ico)?\b|\bmx\b|\bes[ ._-]?(?:la|lat|419|mx|es|us)\b|\bspa[ ._-]?(?:lat|la|mx|cast|es|419)\b|\besp[ ._-]?(?:lat|la|mx|cast|es|419)\b|[._ \-\[\(](?:es|spa|esp|lat|la|mx|es419)[._ \-\]\)]))).*$', 'Rewards releases that appear to include subtitle support for both English and Spanish. This is a strong usability bonus for mixed-language media-server playback.');
INSERT OR REPLACE INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('Subtitles: Prefer English + Spanish', 'Subtitles');
INSERT OR REPLACE INTO regular_expressions (name, pattern, description) VALUES ('Subtitles: English Bonus', '(?i)^(?=.*(?:subs?|subtitles?|srt|vtt|subbed))(?=.*(?:\beng(?:lish)?\b|\btrueenglish\b|\bingles\b|\bingl[e\u00e9]s\b|[._ \-\[\(](?:en|eng|enus)[._ \-\]\)])).*$', 'Small subtitle bonus for English subtitle indicators. Useful when audio language is acceptable but subtitle support is still helpful.');
INSERT OR REPLACE INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('Subtitles: English Bonus', 'Subtitles');
INSERT OR REPLACE INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('Subtitles: English Bonus', 'Scoring');
INSERT OR REPLACE INTO regular_expressions (name, pattern, description) VALUES ('Subtitles: Spanish Bonus', '(?i)^(?=.*(?:subs?|subtitles?|srt|vtt|subbed))(?=.*(?:(?:\bspa(?:nish)?\b|\besp(?:anol|a\u00f1ol)?\b|\bespanol\b|\bespa\u00f1ol\b|\bcastellano\b|\bcastilian\b)|(?:\blatino\b|\blatina\b|\blatam\b|\blatin[ ._-]?america(?:n)?\b|\blatinoamerica(?:no)?\b|\blatinoam[e\u00e9]rica(?:no)?\b|\bespa[n\u00f1]ol[ ._-]?latino\b|\blat(?:ino)?[ ._-]?dub(?:bed)?\b|\baudio[ ._-]?(?:latino|latam|spanish|espa[n\u00f1]ol)\b|\bcast(?:ellano)?\b|\bmex(?:ican|ico)?\b|\bmx\b|\bes[ ._-]?(?:la|lat|419|mx|es|us)\b|\bspa[ ._-]?(?:lat|la|mx|cast|es|419)\b|\besp[ ._-]?(?:lat|la|mx|cast|es|419)\b|[._ \-\[\(](?:es|spa|esp|lat|la|mx|es419)[._ \-\]\)]))).*$', 'Subtitle bonus for Spanish or Latino subtitle indicators. Helps prefer releases that are easier to use for Spanish viewers.');
INSERT OR REPLACE INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('Subtitles: Spanish Bonus', 'Subtitles');
INSERT OR REPLACE INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('Subtitles: Spanish Bonus', 'Scoring');
INSERT OR REPLACE INTO regular_expressions (name, pattern, description) VALUES ('Subtitles: Block Hardcoded-Burned-In', '(?i)\b(?:hardcoded|hardsub(?:bed)?|burn(?:ed)?[ ._-]?in|burnt[ ._-]?in)\b', 'Heavy negative score for hardcoded, hardsubbed, burned-in, or burnt-in subtitle tags. Avoids releases where subtitles cannot be disabled.');
INSERT OR REPLACE INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('Subtitles: Block Hardcoded-Burned-In', 'Subtitles');
INSERT OR REPLACE INTO regular_expression_tags (regular_expression_name, tag_name) VALUES ('Subtitles: Block Hardcoded-Burned-In', 'Blocking');


